name: 'GitOps Pull Request'
description: 'Used for updating a GitOps repo with new image(s)'
inputs:
  ssh-key:
    description: 'SSH key that has read/write access to the GitOps repo'
    required: true
  gitops-repo:
    description: 'GitOps repo to update'
    required: true
  gitops-repo-branch:
    description: 'GitOps repo branch to update'
    required: true
    default: 'master'
  gitops-pr-branch:
    description: 'GitOps branch to be created'
    required: true 
  gitops-file:
    description: 'File to be modified'
    required: true
  gitops-key:
    description: 'Key to be modified'
    required: true
  gitops-value:
    description: 'Value of key to be modified'
    required: true
  changes-by-file:
    description: 'JSON object with changes to make, by file as key'
    required: true
  commit-email:
    description: 'Email address to use for the commit'
    required: true
  commit-name:
    description: 'Name to use for the commit'
    required: true
  commit-mesage:
    description: 'Message to use for the commit'
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout GitOps Repository
    uses: actions/checkout@v3
    with:
      repository: ${{ inputs.gitops-repo }}
      ssh-key: ${{ inputs.ssh-key }}
      path: gitops
  - uses: fjogeleit/yaml-update-action@main
    with:
      branch: deployment/${{ inputs.gitops-branch }}
      targetBranch: master
      createPR: true
      repository: ${{ inputs.gitops-repo }}
      message: ${{ inputs.commit-message }}
      workDir: gitops
      valueFile: ${{ inputs.gitops-file }}
      propertyPath: ${{ inputs.gitops-key }}
      value: ${{ inputs.gitops-value }}
  - name: Push changes
    shell: bash
    run: |
      cd gitops
      git config --global user.email "${{ inputs.commit-email }}"
      git config --global user.name "${{ inputs.commit-name }}"
      git commit -am "${{ inputs.commit-message }}"
      git push
